config/routes.rb
BBRails::Application.routes.draw do
 
  resources :expenses

  resources :rooms

  resources :customers

	get "reservations/calendar"

  resources :reservations

 resources :rooms

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :room
  belongs_to :customer
  attr_accessible :end_date, :start_date ,:room_id, :customer_id


  scope :before, lambda {|end_date| {:conditions => ["end_date < ?", Reservation.format_date(end_date)] }}
  scope :after, lambda {|start_date| {:conditions => ["start_date > ?", Reservation.format_date(start_date)] }}
  
 
  def as_json(options = {})
    {
      :id => self.id,
      :title => self.customer.last_name << " " << self.customer.name,
      :description => self.room.name || "",
      :start => start_date.rfc822,
      :end => end_date.rfc822,
      :allDay => true,
      :recurring => false,
      :color => self.room.uicolor,
      :url => Rails.application.routes.url_helpers.reservation_path(id)
    }
    
  end
  
  def self.format_date(date_time)
    Time.at(date_time.to_i).to_formatted_s(:db)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def calendar	
    @reservations = Reservation.scoped
    @reservations = @reservations.after(params['start']) if (params['start'])
    @reservations = @reservations.before(params['end']) if (params['end'])
    
    respond_to do |format|
      format.html 
      format.json { render :json => @reservations }
    end
	
  end

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reservations }
    end
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/new
  # GET /reservations/new.json
  def new
    @reservation = Reservation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/1/edit
  def edit
    @reservation = Reservation.find(params[:id])
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(params[:reservation])

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render json: @reservation, status: :created, location: @reservation }
      else
        format.html { render action: "new" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reservations/1
  # PUT /reservations/1.json
  def update
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      if @reservation.update_attributes(params[:reservation])
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= simple_form_for @reservation, :html => { :class => 'form-horizontal' } do |f| %>

  <%= f.input :start_date, as: :date, start_year: Date.today.year,
                              end_year: Date.today.year + 5, 
                              order: [:day,:month, :year] %>
 <%= f.input :end_date, as: :date, start_year: Date.today.year,
                              end_year: Date.today.year + 5, 
                              order: [:day,:month, :year] %>  <%= f.association :room %>
  <%= f.association :customer %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                reservations_path, :class => 'btn' %>
  </div>
<% end %>

app/views/reservations/calendar.html.erb
<div id="calendar"></div>

app/views/reservations/edit.html.erb
<%- model_class = Reservation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reservations/index.html.erb
<%- model_class = Reservation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
<p><%=link_to 'Calendar View','reservations/calendar' %></p>

</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:start_date) %></th>
      <th><%= model_class.human_attribute_name(:end_date) %></th>
      <th><%= model_class.human_attribute_name(:room_id) %></th>
      <th><%= model_class.human_attribute_name(:customer_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= link_to reservation.id, reservation_path(reservation) %></td>
        <td><%= reservation.start_date %></td>
        <td><%= reservation.end_date %></td>
        <td><%= reservation.room.name %></td>
        <td><%= link_to(reservation.customer.name << " " << reservation.customer.last_name, edit_customer_path(reservation.customer) ) %></td>
        <td><%=l reservation.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_reservation_path(reservation), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      reservation_path(reservation),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_reservation_path,
            :class => 'btn btn-primary' %>

app/views/reservations/new.html.erb
<%- model_class = Reservation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reservations/show.html.erb
<%- model_class = Reservation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:start_date) %>:</strong></dt>
  <dd><%= @reservation.start_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:end_date) %>:</strong></dt>
  <dd><%= @reservation.end_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:room_id) %>:</strong></dt>
  <dd><%= @reservation.room_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:customer_id) %>:</strong></dt>
  <dd><%= @reservation.customer_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              reservations_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_reservation_path(@reservation), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              reservation_path(@reservation),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>